version: '2'

services:
  composer:
    image: composer:1.6.3
    command: install
    volumes:
      - ./php:/app

  php:
    image: php:7.2.3-cli-alpine3.7
    working_dir: /app
    depends_on:
      - composer
    volumes:
      - ./php:/app
    command: ["./init.sh"]

  js:
    image: node:carbon-alpine
    working_dir: /app
    volumes:
      - ./js:/app
    command: ["./init.sh"]
